version: "3"
services:
  app:
    container_name: app-container
    image: briskcabs
    restart: always
    build: .
    environment:
      - DB_HOST=json-server
    ports:
      - "80:80"
    networks:
      - cabnetwork

  json-server:
    container_name: json-server-container
    image: json-server-image:latest
    build: ./db
    ports:
      - "3000:3000"
    volumes:
      - ./db.json:/data/db.json
    command: json-server --watch db.json --host 0.0.0.0
    networks:
      - cabnetwork
networks:
  cabnetwork:
    driver: bridge

